module(...,package.seeall)
Config={
[1] = {id=1, copyId=1001, copyName="巡回赛第一关", next=2, treasureType=1, attrFactor=.5, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[2] = {id=2, copyId=1002, copyName="巡回赛第二关", next=3, treasureType=1, attrFactor=.52, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[3] = {id=3, copyId=1003, copyName="巡回赛第三关", next=4, treasureType=2, attrFactor=.54, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[4] = {id=4, copyId=1004, copyName="巡回赛第四关", next=5, treasureType=1, attrFactor=.56, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[5] = {id=5, copyId=1005, copyName="巡回赛第五关", next=6, treasureType=1, attrFactor=.58, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[6] = {id=6, copyId=1006, copyName="巡回赛第六关", next=7, treasureType=2, attrFactor=.6, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[7] = {id=7, copyId=1007, copyName="巡回赛第七关", next=8, treasureType=1, attrFactor=.7, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[8] = {id=8, copyId=1008, copyName="巡回赛第八关", next=9, treasureType=1, attrFactor=.72, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[9] = {id=9, copyId=1009, copyName="巡回赛第九关", next=10, treasureType=2, attrFactor=.74, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[10] = {id=10, copyId=1010, copyName="巡回赛第十关", next=11, treasureType=1, attrFactor=.76, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[11] = {id=11, copyId=1011, copyName="巡回赛第十一关", next=12, treasureType=1, attrFactor=.78, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[12] = {id=12, copyId=1012, copyName="巡回赛第十二关", next=13, treasureType=2, attrFactor=.8, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[13] = {id=13, copyId=1013, copyName="巡回赛第十三关", next=14, treasureType=1, attrFactor=.9, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[14] = {id=14, copyId=1014, copyName="巡回赛第十四关", next=15, treasureType=1, attrFactor=.95, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
[15] = {id=15, copyId=1015, copyName="巡回赛第十五关", next=0, treasureType=3, attrFactor=1, skillFactor=1, recType="必杀型英雄", recHero={"Robert","Terry","Athena"}, recDesc="<p><font color='255,255,255'>连击数越高，则造成的伤害也越高</font><br/><br/><font color='255,255,255'>攻略：罗伯特、特瑞、雅典娜通过使用接招和必杀提高连击数。</font></p>", },
}
