module(...,package.seeall)




WIPE_CD = 300
WIPE_CD_RMB = 5

RET_CHAPTER_OK = 0
RET_CHAPTER_NOTPERMITTED = 1
RET_CHAPTER_CDTIME = 2
RET_CHAPTER_PHYSICS = 3
RET_CHAPTER_LEVEL = 4
RET_CHAPTER_TIMES = 5
RET_CHAPTER_RMB = 6  --钻石不足
RET_CHAPTER_RECEIVED = 7
RET_CHAPTER_OVERFLOW = 8 -- 前一个难度的本关卡没有通过，因此需要关闭本关卡
RET_CHAPTER_TICKET = 9  -- 历练券不足
RET_CHAPTER_NOTOPENED = 10 -- 本关卡未开放，无法通过
RET_CHAPTER_IGNORED = 11 -- 本请求被服务端忽略
RET_CHAPTER_NOTPASSED = 12 -- 本关卡未通过，不允许扫荡
RET_CHAPTER_LILIAN_LEVEL = 13  -- 历练功能等级限制
RET_CHAPTER_BUYTIMES = 14  -- 购买次数达到上限
RET_CHAPTER_STAR = 15      -- 星星数不足

WIN       = 0
DEFEATED  = 1

MAX_RANK = 50

WIPE_TICKET_ITEMID = 1902001
ENERGY_ITEMID      = 1903001
BUTTIMES_SHOPID = 1004

LILIAN_LEVEL  = 15  -- 开启历练功能的战队等级限制